# Generated by Django 2.2.4 on 2020-01-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_des', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
